Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-14.04-amd64"
  config.vm.provision :shell, :privileged => false, :path => "build.sh"
  config.vbguest.auto_update = true
  config.vbguest.auto_reboot = true

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "8192"]
    vb.customize ["modifyvm", :id, "--cpus", "8"]
  end
end
