Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-14.04-i386"
  config.vm.provision :shell, :privileged => false, :path => "bootstrap.sh"
  config.vbguest.auto_update = true
  config.vbguest.auto_reboot = true

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
  end
end
